//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Main
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Recepta
    {
        public int Id { get; set; }
        public int IdLeku { get; set; }
        public int NumerRecepty { get; set; }
        public string PESEL { get; set; }
        public bool CzyZrealizowano { get; set; }
    
        public virtual tbl_Leki tbl_Leki { get; set; }
    }
}
