//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Main
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Sprzedaz
    {
        public int IdSprzedazy { get; set; }
        public int IdLekuSprzedanego { get; set; }
        public System.DateTime DataSprzedazy { get; set; }
        public int IdAptekarza { get; set; }
    
        public virtual tbl_Leki tbl_Leki { get; set; }
    }
}
